; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s --check-prefix=SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx2 | FileCheck %s --check-prefixes=AVX,AVX2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f | FileCheck %s --check-prefixes=AVX,AVX512F
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512bw | FileCheck %s --check-prefixes=AVX,AVX512BW

; InstCombine can factor a common shift and truncation out of an OR of
; high-half products. Recover PMULHUW/PMULHW from the widened form.

define <8 x i16> @zext_or_mulh_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d) {
; SSE2-LABEL: zext_or_mulh_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pmulhuw %xmm1, %xmm0
; SSE2-NEXT:    pmulhuw %xmm3, %xmm2
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: zext_or_mulh_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhuw %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vpmulhuw %xmm3, %xmm2, %xmm1
; AVX-NEXT:    vpor %xmm0, %xmm1, %xmm0
; AVX-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  %joined = or <8 x i32> %ab, %cd
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @sext_or_mulh_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d) {
; SSE2-LABEL: sext_or_mulh_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pmulhw %xmm1, %xmm0
; SSE2-NEXT:    pmulhw %xmm3, %xmm2
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: sext_or_mulh_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhw %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vpmulhw %xmm3, %xmm2, %xmm1
; AVX-NEXT:    vpor %xmm0, %xmm1, %xmm0
; AVX-NEXT:    retq
  %aw = sext <8 x i16> %a to <8 x i32>
  %bw = sext <8 x i16> %b to <8 x i32>
  %cw = sext <8 x i16> %c to <8 x i32>
  %dw = sext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  %joined = or <8 x i32> %ab, %cd
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @mixed_or_mulh_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d) {
; SSE2-LABEL: mixed_or_mulh_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pmulhw %xmm1, %xmm0
; SSE2-NEXT:    pmulhuw %xmm3, %xmm2
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: mixed_or_mulh_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhw %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vpmulhuw %xmm3, %xmm2, %xmm1
; AVX-NEXT:    vpor %xmm0, %xmm1, %xmm0
; AVX-NEXT:    retq
  %aw = sext <8 x i16> %a to <8 x i32>
  %bw = sext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  %joined = or <8 x i32> %ab, %cd
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <16 x i16> @zext_or_mulh_v16i16(<16 x i16> %a, <16 x i16> %b, <16 x i16> %c, <16 x i16> %d) {
; SSE2-LABEL: zext_or_mulh_v16i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pmulhuw %xmm2, %xmm0
; SSE2-NEXT:    pmulhuw %xmm6, %xmm4
; SSE2-NEXT:    por %xmm4, %xmm0
; SSE2-NEXT:    pmulhuw %xmm3, %xmm1
; SSE2-NEXT:    pmulhuw %xmm7, %xmm5
; SSE2-NEXT:    por %xmm5, %xmm1
; SSE2-NEXT:    retq
;
; AVX-LABEL: zext_or_mulh_v16i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhuw %ymm1, %ymm0, %ymm0
; AVX-NEXT:    vpmulhuw %ymm3, %ymm2, %ymm1
; AVX-NEXT:    vpor %ymm0, %ymm1, %ymm0
; AVX-NEXT:    retq
  %aw = zext <16 x i16> %a to <16 x i32>
  %bw = zext <16 x i16> %b to <16 x i32>
  %cw = zext <16 x i16> %c to <16 x i32>
  %dw = zext <16 x i16> %d to <16 x i32>
  %ab = mul <16 x i32> %aw, %bw
  %cd = mul <16 x i32> %cw, %dw
  %joined = or <16 x i32> %ab, %cd
  %high = lshr <16 x i32> %joined, splat (i32 16)
  %result = trunc <16 x i32> %high to <16 x i16>
  ret <16 x i16> %result
}

define <32 x i16> @zext_or_mulh_v32i16(<32 x i16> %a, <32 x i16> %b, <32 x i16> %c, <32 x i16> %d) {
; SSE2-LABEL: zext_or_mulh_v32i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{[0-9]+}}(%rsp), %xmm8
; SSE2-NEXT:    movdqa {{[0-9]+}}(%rsp), %xmm9
; SSE2-NEXT:    movdqa {{[0-9]+}}(%rsp), %xmm10
; SSE2-NEXT:    movdqa {{[0-9]+}}(%rsp), %xmm11
; SSE2-NEXT:    pmulhuw %xmm4, %xmm0
; SSE2-NEXT:    pmulhuw {{[0-9]+}}(%rsp), %xmm11
; SSE2-NEXT:    por %xmm11, %xmm0
; SSE2-NEXT:    pmulhuw %xmm5, %xmm1
; SSE2-NEXT:    pmulhuw {{[0-9]+}}(%rsp), %xmm10
; SSE2-NEXT:    por %xmm10, %xmm1
; SSE2-NEXT:    pmulhuw %xmm6, %xmm2
; SSE2-NEXT:    pmulhuw {{[0-9]+}}(%rsp), %xmm9
; SSE2-NEXT:    por %xmm9, %xmm2
; SSE2-NEXT:    pmulhuw %xmm7, %xmm3
; SSE2-NEXT:    pmulhuw {{[0-9]+}}(%rsp), %xmm8
; SSE2-NEXT:    por %xmm8, %xmm3
; SSE2-NEXT:    retq
;
; AVX2-LABEL: zext_or_mulh_v32i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmulhuw %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpmulhuw %ymm6, %ymm4, %ymm2
; AVX2-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    vpmulhuw %ymm3, %ymm1, %ymm1
; AVX2-NEXT:    vpmulhuw %ymm7, %ymm5, %ymm2
; AVX2-NEXT:    vpor %ymm1, %ymm2, %ymm1
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: zext_or_mulh_v32i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vextracti64x4 $1, %zmm1, %ymm4
; AVX512F-NEXT:    vextracti64x4 $1, %zmm0, %ymm5
; AVX512F-NEXT:    vpmulhuw %ymm4, %ymm5, %ymm4
; AVX512F-NEXT:    vpmulhuw %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vinserti64x4 $1, %ymm4, %zmm0, %zmm0
; AVX512F-NEXT:    vextracti64x4 $1, %zmm3, %ymm1
; AVX512F-NEXT:    vextracti64x4 $1, %zmm2, %ymm4
; AVX512F-NEXT:    vpmulhuw %ymm1, %ymm4, %ymm1
; AVX512F-NEXT:    vpmulhuw %ymm3, %ymm2, %ymm2
; AVX512F-NEXT:    vinserti64x4 $1, %ymm1, %zmm2, %zmm1
; AVX512F-NEXT:    vporq %zmm0, %zmm1, %zmm0
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: zext_or_mulh_v32i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmulhuw %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vpmulhuw %zmm3, %zmm2, %zmm1
; AVX512BW-NEXT:    vporq %zmm0, %zmm1, %zmm0
; AVX512BW-NEXT:    retq
  %aw = zext <32 x i16> %a to <32 x i32>
  %bw = zext <32 x i16> %b to <32 x i32>
  %cw = zext <32 x i16> %c to <32 x i32>
  %dw = zext <32 x i16> %d to <32 x i32>
  %ab = mul <32 x i32> %aw, %bw
  %cd = mul <32 x i32> %cw, %dw
  %joined = or <32 x i32> %ab, %cd
  %high = lshr <32 x i32> %joined, splat (i32 16)
  %result = trunc <32 x i32> %high to <32 x i16>
  ret <32 x i16> %result
}

define <4 x i16> @sext_or_mulh_wide_v4i16(<4 x i16> %a, <4 x i16> %b, <4 x i16> %c, <4 x i16> %d) {
; SSE2-LABEL: sext_or_mulh_wide_v4i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pmulhw %xmm1, %xmm0
; SSE2-NEXT:    pmulhw %xmm3, %xmm2
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: sext_or_mulh_wide_v4i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhw %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vpmulhw %xmm3, %xmm2, %xmm1
; AVX-NEXT:    vpor %xmm0, %xmm1, %xmm0
; AVX-NEXT:    retq
  %aw = sext <4 x i16> %a to <4 x i64>
  %bw = sext <4 x i16> %b to <4 x i64>
  %cw = sext <4 x i16> %c to <4 x i64>
  %dw = sext <4 x i16> %d to <4 x i64>
  %ab = mul <4 x i64> %aw, %bw
  %cd = mul <4 x i64> %cw, %dw
  %joined = or <4 x i64> %ab, %cd
  %high = lshr <4 x i64> %joined, splat (i64 16)
  %result = trunc <4 x i64> %high to <4 x i16>
  ret <4 x i16> %result
}

define <4 x i16> @sext_or_shift17_wide_v4i16(<4 x i16> %a, <4 x i16> %b, <4 x i16> %c, <4 x i16> %d) {
; SSE2-LABEL: sext_or_shift17_wide_v4i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm12 = xmm12[0],xmm0[0],xmm12[1],xmm0[1],xmm12[2],xmm0[2],xmm12[3],xmm0[3]
; SSE2-NEXT:    psrad $16, %xmm12
; SSE2-NEXT:    pxor %xmm4, %xmm4
; SSE2-NEXT:    pxor %xmm7, %xmm7
; SSE2-NEXT:    pcmpgtd %xmm12, %xmm7
; SSE2-NEXT:    movdqa %xmm12, %xmm9
; SSE2-NEXT:    punpckldq {{.*#+}} xmm9 = xmm9[0],xmm7[0],xmm9[1],xmm7[1]
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm12 = xmm12[2],xmm7[2],xmm12[3],xmm7[3]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm13 = xmm13[0],xmm1[0],xmm13[1],xmm1[1],xmm13[2],xmm1[2],xmm13[3],xmm1[3]
; SSE2-NEXT:    psrad $16, %xmm13
; SSE2-NEXT:    pxor %xmm1, %xmm1
; SSE2-NEXT:    pcmpgtd %xmm13, %xmm1
; SSE2-NEXT:    movdqa %xmm13, %xmm11
; SSE2-NEXT:    punpckldq {{.*#+}} xmm11 = xmm11[0],xmm1[0],xmm11[1],xmm1[1]
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm13 = xmm13[2],xmm1[2],xmm13[3],xmm1[3]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm6 = xmm6[0],xmm2[0],xmm6[1],xmm2[1],xmm6[2],xmm2[2],xmm6[3],xmm2[3]
; SSE2-NEXT:    psrad $16, %xmm6
; SSE2-NEXT:    pxor %xmm2, %xmm2
; SSE2-NEXT:    pcmpgtd %xmm6, %xmm2
; SSE2-NEXT:    movdqa %xmm6, %xmm5
; SSE2-NEXT:    punpckldq {{.*#+}} xmm5 = xmm5[0],xmm2[0],xmm5[1],xmm2[1]
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm6 = xmm6[2],xmm2[2],xmm6[3],xmm2[3]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm8 = xmm8[0],xmm3[0],xmm8[1],xmm3[1],xmm8[2],xmm3[2],xmm8[3],xmm3[3]
; SSE2-NEXT:    psrad $16, %xmm8
; SSE2-NEXT:    pxor %xmm0, %xmm0
; SSE2-NEXT:    pcmpgtd %xmm8, %xmm0
; SSE2-NEXT:    movdqa %xmm8, %xmm3
; SSE2-NEXT:    punpckldq {{.*#+}} xmm3 = xmm3[0],xmm0[0],xmm3[1],xmm0[1]
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm8 = xmm8[2],xmm0[2],xmm8[3],xmm0[3]
; SSE2-NEXT:    movdqa %xmm1, %xmm10
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm10 = xmm10[2],xmm4[2],xmm10[3],xmm4[3]
; SSE2-NEXT:    pmuludq %xmm12, %xmm10
; SSE2-NEXT:    pmuludq %xmm13, %xmm12
; SSE2-NEXT:    movdqa %xmm7, %xmm14
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm14 = xmm14[2],xmm4[2],xmm14[3],xmm4[3]
; SSE2-NEXT:    pmuludq %xmm13, %xmm14
; SSE2-NEXT:    paddq %xmm14, %xmm10
; SSE2-NEXT:    psllq $32, %xmm10
; SSE2-NEXT:    paddq %xmm12, %xmm10
; SSE2-NEXT:    punpckldq {{.*#+}} xmm1 = xmm1[0],xmm4[0],xmm1[1],xmm4[1]
; SSE2-NEXT:    pmuludq %xmm9, %xmm1
; SSE2-NEXT:    pmuludq %xmm11, %xmm9
; SSE2-NEXT:    punpckldq {{.*#+}} xmm7 = xmm7[0],xmm4[0],xmm7[1],xmm4[1]
; SSE2-NEXT:    pmuludq %xmm11, %xmm7
; SSE2-NEXT:    paddq %xmm7, %xmm1
; SSE2-NEXT:    psllq $32, %xmm1
; SSE2-NEXT:    paddq %xmm9, %xmm1
; SSE2-NEXT:    movdqa %xmm0, %xmm7
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm7 = xmm7[2],xmm4[2],xmm7[3],xmm4[3]
; SSE2-NEXT:    pmuludq %xmm6, %xmm7
; SSE2-NEXT:    pmuludq %xmm8, %xmm6
; SSE2-NEXT:    movdqa %xmm2, %xmm9
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm9 = xmm9[2],xmm4[2],xmm9[3],xmm4[3]
; SSE2-NEXT:    pmuludq %xmm8, %xmm9
; SSE2-NEXT:    paddq %xmm9, %xmm7
; SSE2-NEXT:    psllq $32, %xmm7
; SSE2-NEXT:    paddq %xmm6, %xmm7
; SSE2-NEXT:    por %xmm10, %xmm7
; SSE2-NEXT:    punpckldq {{.*#+}} xmm0 = xmm0[0],xmm4[0],xmm0[1],xmm4[1]
; SSE2-NEXT:    pmuludq %xmm5, %xmm0
; SSE2-NEXT:    pmuludq %xmm3, %xmm5
; SSE2-NEXT:    punpckldq {{.*#+}} xmm2 = xmm2[0],xmm4[0],xmm2[1],xmm4[1]
; SSE2-NEXT:    pmuludq %xmm3, %xmm2
; SSE2-NEXT:    paddq %xmm2, %xmm0
; SSE2-NEXT:    psllq $32, %xmm0
; SSE2-NEXT:    paddq %xmm5, %xmm0
; SSE2-NEXT:    por %xmm1, %xmm0
; SSE2-NEXT:    psrlq $17, %xmm7
; SSE2-NEXT:    psrlq $17, %xmm0
; SSE2-NEXT:    shufps {{.*#+}} xmm0 = xmm0[0,2],xmm7[0,2]
; SSE2-NEXT:    pslld $16, %xmm0
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm4, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: sext_or_shift17_wide_v4i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovsxwq %xmm0, %ymm0
; AVX2-NEXT:    vpmovsxwq %xmm1, %ymm1
; AVX2-NEXT:    vpmuldq %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpmovsxwq %xmm2, %ymm1
; AVX2-NEXT:    vpmovsxwq %xmm3, %ymm2
; AVX2-NEXT:    vpmuldq %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpsrlq $17, %ymm0, %ymm0
; AVX2-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vpblendw {{.*#+}} ymm0 = ymm0[0],ymm1[1,2,3],ymm0[4],ymm1[5,6,7],ymm0[8],ymm1[9,10,11],ymm0[12],ymm1[13,14,15]
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpackusdw %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: sext_or_shift17_wide_v4i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovsxwq %xmm0, %ymm0
; AVX512F-NEXT:    vpmovsxwq %xmm1, %ymm1
; AVX512F-NEXT:    vpmuldq %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovsxwq %xmm2, %ymm1
; AVX512F-NEXT:    vpmovsxwq %xmm3, %ymm2
; AVX512F-NEXT:    vpmuldq %ymm2, %ymm1, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrlq $17, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovqw %zmm0, %xmm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: sext_or_shift17_wide_v4i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovsxwq %xmm0, %ymm0
; AVX512BW-NEXT:    vpmovsxwq %xmm1, %ymm1
; AVX512BW-NEXT:    vpmuldq %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovsxwq %xmm2, %ymm1
; AVX512BW-NEXT:    vpmovsxwq %xmm3, %ymm2
; AVX512BW-NEXT:    vpmuldq %ymm2, %ymm1, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrlq $17, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovqw %zmm0, %xmm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = sext <4 x i16> %a to <4 x i64>
  %bw = sext <4 x i16> %b to <4 x i64>
  %cw = sext <4 x i16> %c to <4 x i64>
  %dw = sext <4 x i16> %d to <4 x i64>
  %ab = mul <4 x i64> %aw, %bw
  %cd = mul <4 x i64> %cw, %dw
  %joined = or <4 x i64> %ab, %cd
  %high = lshr <4 x i64> %joined, splat (i64 17)
  %result = trunc <4 x i64> %high to <4 x i16>
  ret <4 x i16> %result
}

define <8 x i16> @zext_or_mulh_shared_product_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d, ptr %p) {
; SSE2-LABEL: zext_or_mulh_shared_product_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm0, %xmm4
; SSE2-NEXT:    pmulhuw %xmm1, %xmm4
; SSE2-NEXT:    pmullw %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm1 = xmm1[0],xmm4[0],xmm1[1],xmm4[1],xmm1[2],xmm4[2],xmm1[3],xmm4[3]
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm0 = xmm0[4],xmm4[4],xmm0[5],xmm4[5],xmm0[6],xmm4[6],xmm0[7],xmm4[7]
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pmulhuw %xmm3, %xmm4
; SSE2-NEXT:    pmullw %xmm3, %xmm2
; SSE2-NEXT:    movdqa %xmm2, %xmm3
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm3 = xmm3[4],xmm4[4],xmm3[5],xmm4[5],xmm3[6],xmm4[6],xmm3[7],xmm4[7]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm2 = xmm2[0],xmm4[0],xmm2[1],xmm4[1],xmm2[2],xmm4[2],xmm2[3],xmm4[3]
; SSE2-NEXT:    movdqa %xmm0, 16(%rdi)
; SSE2-NEXT:    movdqa %xmm1, (%rdi)
; SSE2-NEXT:    por %xmm2, %xmm1
; SSE2-NEXT:    por %xmm0, %xmm3
; SSE2-NEXT:    psrad $16, %xmm3
; SSE2-NEXT:    psrad $16, %xmm1
; SSE2-NEXT:    packssdw %xmm3, %xmm1
; SSE2-NEXT:    movdqa %xmm1, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: zext_or_mulh_shared_product_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX2-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX2-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: zext_or_mulh_shared_product_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512F-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX512F-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX512F-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: zext_or_mulh_shared_product_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512BW-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX512BW-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX512BW-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  store volatile <8 x i32> %ab, ptr %p
  %joined = or <8 x i32> %ab, %cd
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @zext_or_mulh_shared_or_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d, ptr %p) {
; SSE2-LABEL: zext_or_mulh_shared_or_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm0, %xmm4
; SSE2-NEXT:    pmulhuw %xmm1, %xmm4
; SSE2-NEXT:    pmullw %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm4[4],xmm1[5],xmm4[5],xmm1[6],xmm4[6],xmm1[7],xmm4[7]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0],xmm4[0],xmm0[1],xmm4[1],xmm0[2],xmm4[2],xmm0[3],xmm4[3]
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pmulhuw %xmm3, %xmm4
; SSE2-NEXT:    pmullw %xmm3, %xmm2
; SSE2-NEXT:    movdqa %xmm2, %xmm3
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm3 = xmm3[4],xmm4[4],xmm3[5],xmm4[5],xmm3[6],xmm4[6],xmm3[7],xmm4[7]
; SSE2-NEXT:    por %xmm1, %xmm3
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm2 = xmm2[0],xmm4[0],xmm2[1],xmm4[1],xmm2[2],xmm4[2],xmm2[3],xmm4[3]
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    movdqa %xmm3, 16(%rdi)
; SSE2-NEXT:    movdqa %xmm0, (%rdi)
; SSE2-NEXT:    psrad $16, %xmm3
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm3, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: zext_or_mulh_shared_or_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX2-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: zext_or_mulh_shared_or_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512F-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: zext_or_mulh_shared_or_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512BW-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  %joined = or <8 x i32> %ab, %cd
  store volatile <8 x i32> %joined, ptr %p
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @zext_or_mulh_shared_shift_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d, ptr %p) {
; SSE2-LABEL: zext_or_mulh_shared_shift_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm0, %xmm4
; SSE2-NEXT:    pmulhuw %xmm1, %xmm4
; SSE2-NEXT:    pmullw %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm5
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm5 = xmm5[0],xmm4[0],xmm5[1],xmm4[1],xmm5[2],xmm4[2],xmm5[3],xmm4[3]
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm0 = xmm0[4],xmm4[4],xmm0[5],xmm4[5],xmm0[6],xmm4[6],xmm0[7],xmm4[7]
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pmulhuw %xmm3, %xmm4
; SSE2-NEXT:    pmullw %xmm3, %xmm2
; SSE2-NEXT:    movdqa %xmm2, %xmm1
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm1 = xmm1[0],xmm4[0],xmm1[1],xmm4[1],xmm1[2],xmm4[2],xmm1[3],xmm4[3]
; SSE2-NEXT:    por %xmm5, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm2 = xmm2[4],xmm4[4],xmm2[5],xmm4[5],xmm2[6],xmm4[6],xmm2[7],xmm4[7]
; SSE2-NEXT:    por %xmm0, %xmm2
; SSE2-NEXT:    movdqa %xmm1, %xmm0
; SSE2-NEXT:    psrld $16, %xmm0
; SSE2-NEXT:    movdqa %xmm2, %xmm3
; SSE2-NEXT:    psrld $16, %xmm3
; SSE2-NEXT:    movdqa %xmm3, 16(%rdi)
; SSE2-NEXT:    movdqa %xmm0, (%rdi)
; SSE2-NEXT:    psrad $16, %xmm2
; SSE2-NEXT:    psrad $16, %xmm1
; SSE2-NEXT:    packssdw %xmm2, %xmm1
; SSE2-NEXT:    movdqa %xmm1, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: zext_or_mulh_shared_shift_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX2-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: zext_or_mulh_shared_shift_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512F-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: zext_or_mulh_shared_shift_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512BW-NEXT:    vpmulld %ymm2, %ymm1, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vmovdqa %ymm0, (%rdi)
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  %joined = or <8 x i32> %ab, %cd
  %high = lshr <8 x i32> %joined, splat (i32 16)
  store volatile <8 x i32> %high, ptr %p
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @zext_or_mulh_balanced_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d) {
; SSE2-LABEL: zext_or_mulh_balanced_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm1, %xmm4
; SSE2-NEXT:    pmulhuw %xmm2, %xmm4
; SSE2-NEXT:    pmulhuw %xmm3, %xmm2
; SSE2-NEXT:    pmulhuw %xmm0, %xmm3
; SSE2-NEXT:    por %xmm2, %xmm3
; SSE2-NEXT:    pmulhuw %xmm1, %xmm0
; SSE2-NEXT:    por %xmm4, %xmm0
; SSE2-NEXT:    por %xmm3, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: zext_or_mulh_balanced_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhuw %xmm3, %xmm2, %xmm4
; AVX-NEXT:    vpmulhuw %xmm0, %xmm3, %xmm3
; AVX-NEXT:    vpor %xmm4, %xmm3, %xmm3
; AVX-NEXT:    vpmulhuw %xmm2, %xmm1, %xmm2
; AVX-NEXT:    vpmulhuw %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vpor %xmm0, %xmm2, %xmm0
; AVX-NEXT:    vpor %xmm0, %xmm3, %xmm0
; AVX-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %p0 = mul <8 x i32> %aw, %bw
  %p1 = mul <8 x i32> %bw, %cw
  %p2 = mul <8 x i32> %cw, %dw
  %p3 = mul <8 x i32> %dw, %aw
  %or0 = or <8 x i32> %p0, %p1
  %or1 = or <8 x i32> %p2, %p3
  %or2 = or <8 x i32> %or0, %or1
  %high = lshr <8 x i32> %or2, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @zext_or_mulh_eight_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d, <8 x i16> %e, <8 x i16> %f, <8 x i16> %g, <8 x i16> %h) {
; SSE2-LABEL: zext_or_mulh_eight_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm1, %xmm8
; SSE2-NEXT:    pmulhuw %xmm2, %xmm8
; SSE2-NEXT:    pmulhuw %xmm3, %xmm2
; SSE2-NEXT:    pmulhuw %xmm4, %xmm3
; SSE2-NEXT:    pmulhuw %xmm5, %xmm4
; SSE2-NEXT:    pmulhuw %xmm6, %xmm5
; SSE2-NEXT:    pmulhuw %xmm7, %xmm6
; SSE2-NEXT:    pmulhuw %xmm0, %xmm7
; SSE2-NEXT:    por %xmm6, %xmm7
; SSE2-NEXT:    por %xmm4, %xmm5
; SSE2-NEXT:    por %xmm7, %xmm5
; SSE2-NEXT:    por %xmm2, %xmm3
; SSE2-NEXT:    por %xmm8, %xmm3
; SSE2-NEXT:    por %xmm5, %xmm3
; SSE2-NEXT:    pmulhuw %xmm1, %xmm0
; SSE2-NEXT:    por %xmm3, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: zext_or_mulh_eight_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhuw %xmm7, %xmm6, %xmm8
; AVX-NEXT:    vpmulhuw %xmm0, %xmm7, %xmm7
; AVX-NEXT:    vpor %xmm7, %xmm8, %xmm7
; AVX-NEXT:    vpmulhuw %xmm6, %xmm5, %xmm6
; AVX-NEXT:    vpmulhuw %xmm5, %xmm4, %xmm5
; AVX-NEXT:    vpor %xmm5, %xmm6, %xmm5
; AVX-NEXT:    vpor %xmm5, %xmm7, %xmm5
; AVX-NEXT:    vpmulhuw %xmm4, %xmm3, %xmm4
; AVX-NEXT:    vpmulhuw %xmm3, %xmm2, %xmm3
; AVX-NEXT:    vpor %xmm3, %xmm4, %xmm3
; AVX-NEXT:    vpmulhuw %xmm2, %xmm1, %xmm2
; AVX-NEXT:    vpor %xmm2, %xmm3, %xmm2
; AVX-NEXT:    vpor %xmm2, %xmm5, %xmm2
; AVX-NEXT:    vpmulhuw %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vpor %xmm0, %xmm2, %xmm0
; AVX-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ew = zext <8 x i16> %e to <8 x i32>
  %fw = zext <8 x i16> %f to <8 x i32>
  %gw = zext <8 x i16> %g to <8 x i32>
  %hw = zext <8 x i16> %h to <8 x i32>
  %p0 = mul <8 x i32> %aw, %bw
  %p1 = mul <8 x i32> %bw, %cw
  %p2 = mul <8 x i32> %cw, %dw
  %p3 = mul <8 x i32> %dw, %ew
  %p4 = mul <8 x i32> %ew, %fw
  %p5 = mul <8 x i32> %fw, %gw
  %p6 = mul <8 x i32> %gw, %hw
  %p7 = mul <8 x i32> %hw, %aw
  %or0 = or <8 x i32> %p0, %p1
  %or1 = or <8 x i32> %or0, %p2
  %or2 = or <8 x i32> %or1, %p3
  %or3 = or <8 x i32> %or2, %p4
  %or4 = or <8 x i32> %or3, %p5
  %or5 = or <8 x i32> %or4, %p6
  %or6 = or <8 x i32> %or5, %p7
  %high = lshr <8 x i32> %or6, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @zext_or_mulh_nine_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d, <8 x i16> %e) {
; SSE2-LABEL: zext_or_mulh_nine_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm1, %xmm14
; SSE2-NEXT:    movdqa %xmm0, %xmm5
; SSE2-NEXT:    pmulhuw %xmm1, %xmm5
; SSE2-NEXT:    movdqa %xmm0, %xmm7
; SSE2-NEXT:    pmullw %xmm1, %xmm7
; SSE2-NEXT:    movdqa %xmm7, %xmm8
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm8 = xmm8[0],xmm5[0],xmm8[1],xmm5[1],xmm8[2],xmm5[2],xmm8[3],xmm5[3]
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm7 = xmm7[4],xmm5[4],xmm7[5],xmm5[5],xmm7[6],xmm5[6],xmm7[7],xmm5[7]
; SSE2-NEXT:    movdqa %xmm1, %xmm9
; SSE2-NEXT:    pmulhuw %xmm2, %xmm9
; SSE2-NEXT:    movdqa %xmm1, %xmm5
; SSE2-NEXT:    pmullw %xmm2, %xmm5
; SSE2-NEXT:    movdqa %xmm5, %xmm6
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm6 = xmm6[0],xmm9[0],xmm6[1],xmm9[1],xmm6[2],xmm9[2],xmm6[3],xmm9[3]
; SSE2-NEXT:    por %xmm8, %xmm6
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm5 = xmm5[4],xmm9[4],xmm5[5],xmm9[5],xmm5[6],xmm9[6],xmm5[7],xmm9[7]
; SSE2-NEXT:    por %xmm7, %xmm5
; SSE2-NEXT:    movdqa %xmm2, %xmm7
; SSE2-NEXT:    pmulhuw %xmm3, %xmm7
; SSE2-NEXT:    movdqa %xmm2, %xmm9
; SSE2-NEXT:    pmullw %xmm3, %xmm9
; SSE2-NEXT:    movdqa %xmm9, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm7[4],xmm1[5],xmm7[5],xmm1[6],xmm7[6],xmm1[7],xmm7[7]
; SSE2-NEXT:    movdqa %xmm1, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm9 = xmm9[0],xmm7[0],xmm9[1],xmm7[1],xmm9[2],xmm7[2],xmm9[3],xmm7[3]
; SSE2-NEXT:    movdqa %xmm3, %xmm1
; SSE2-NEXT:    movdqa %xmm4, %xmm8
; SSE2-NEXT:    movdqa %xmm4, %xmm11
; SSE2-NEXT:    pmulhuw %xmm0, %xmm11
; SSE2-NEXT:    movdqa %xmm4, %xmm10
; SSE2-NEXT:    pmullw %xmm0, %xmm10
; SSE2-NEXT:    movdqa %xmm0, %xmm13
; SSE2-NEXT:    movdqa %xmm0, %xmm12
; SSE2-NEXT:    movdqa %xmm14, %xmm4
; SSE2-NEXT:    pmulhuw %xmm3, %xmm4
; SSE2-NEXT:    pmullw %xmm3, %xmm14
; SSE2-NEXT:    movdqa %xmm3, %xmm15
; SSE2-NEXT:    pmulhuw %xmm0, %xmm15
; SSE2-NEXT:    pmullw %xmm3, %xmm0
; SSE2-NEXT:    pmulhuw %xmm8, %xmm3
; SSE2-NEXT:    pmullw %xmm8, %xmm1
; SSE2-NEXT:    movdqa %xmm1, %xmm7
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm7 = xmm7[0],xmm3[0],xmm7[1],xmm3[1],xmm7[2],xmm3[2],xmm7[3],xmm3[3]
; SSE2-NEXT:    por %xmm9, %xmm7
; SSE2-NEXT:    por %xmm6, %xmm7
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm3[4],xmm1[5],xmm3[5],xmm1[6],xmm3[6],xmm1[7],xmm3[7]
; SSE2-NEXT:    por {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Folded Reload
; SSE2-NEXT:    por %xmm5, %xmm1
; SSE2-NEXT:    movdqa %xmm10, %xmm3
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm3 = xmm3[4],xmm11[4],xmm3[5],xmm11[5],xmm3[6],xmm11[6],xmm3[7],xmm11[7]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm10 = xmm10[0],xmm11[0],xmm10[1],xmm11[1],xmm10[2],xmm11[2],xmm10[3],xmm11[3]
; SSE2-NEXT:    pmulhuw %xmm2, %xmm13
; SSE2-NEXT:    pmullw %xmm2, %xmm12
; SSE2-NEXT:    movdqa %xmm12, %xmm5
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm5 = xmm5[0],xmm13[0],xmm5[1],xmm13[1],xmm5[2],xmm13[2],xmm5[3],xmm13[3]
; SSE2-NEXT:    por %xmm10, %xmm5
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm12 = xmm12[4],xmm13[4],xmm12[5],xmm13[5],xmm12[6],xmm13[6],xmm12[7],xmm13[7]
; SSE2-NEXT:    por %xmm3, %xmm12
; SSE2-NEXT:    movdqa %xmm14, %xmm3
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm3 = xmm3[4],xmm4[4],xmm3[5],xmm4[5],xmm3[6],xmm4[6],xmm3[7],xmm4[7]
; SSE2-NEXT:    por %xmm12, %xmm3
; SSE2-NEXT:    por %xmm1, %xmm3
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm14 = xmm14[0],xmm4[0],xmm14[1],xmm4[1],xmm14[2],xmm4[2],xmm14[3],xmm4[3]
; SSE2-NEXT:    por %xmm14, %xmm5
; SSE2-NEXT:    por %xmm7, %xmm5
; SSE2-NEXT:    movdqa %xmm2, %xmm1
; SSE2-NEXT:    pmulhuw %xmm8, %xmm1
; SSE2-NEXT:    pmullw %xmm8, %xmm2
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm4 = xmm4[0],xmm1[0],xmm4[1],xmm1[1],xmm4[2],xmm1[2],xmm4[3],xmm1[3]
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm2 = xmm2[4],xmm1[4],xmm2[5],xmm1[5],xmm2[6],xmm1[6],xmm2[7],xmm1[7]
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm15[4],xmm1[5],xmm15[5],xmm1[6],xmm15[6],xmm1[7],xmm15[7]
; SSE2-NEXT:    por %xmm2, %xmm1
; SSE2-NEXT:    por %xmm3, %xmm1
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0],xmm15[0],xmm0[1],xmm15[1],xmm0[2],xmm15[2],xmm0[3],xmm15[3]
; SSE2-NEXT:    por %xmm4, %xmm0
; SSE2-NEXT:    por %xmm5, %xmm0
; SSE2-NEXT:    psrad $16, %xmm1
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm1, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: zext_or_mulh_nine_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm3 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm4 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero
; AVX2-NEXT:    vpmulld %ymm1, %ymm0, %ymm5
; AVX2-NEXT:    vpmulld %ymm2, %ymm1, %ymm6
; AVX2-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX2-NEXT:    vpmulld %ymm3, %ymm2, %ymm6
; AVX2-NEXT:    vpmulld %ymm4, %ymm3, %ymm7
; AVX2-NEXT:    vpor %ymm7, %ymm6, %ymm6
; AVX2-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX2-NEXT:    vpmulld %ymm0, %ymm4, %ymm6
; AVX2-NEXT:    vpmulld %ymm2, %ymm0, %ymm7
; AVX2-NEXT:    vpor %ymm7, %ymm6, %ymm6
; AVX2-NEXT:    vpmulld %ymm3, %ymm1, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm6, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm5, %ymm1
; AVX2-NEXT:    vpmulld %ymm4, %ymm2, %ymm2
; AVX2-NEXT:    vpmulld %ymm0, %ymm3, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: zext_or_mulh_nine_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm3 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm4 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero
; AVX512F-NEXT:    vpmulld %ymm1, %ymm0, %ymm5
; AVX512F-NEXT:    vpmulld %ymm2, %ymm1, %ymm6
; AVX512F-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX512F-NEXT:    vpmulld %ymm3, %ymm2, %ymm6
; AVX512F-NEXT:    vpmulld %ymm4, %ymm3, %ymm7
; AVX512F-NEXT:    vpor %ymm7, %ymm6, %ymm6
; AVX512F-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX512F-NEXT:    vpmulld %ymm0, %ymm4, %ymm6
; AVX512F-NEXT:    vpmulld %ymm2, %ymm0, %ymm7
; AVX512F-NEXT:    vpor %ymm7, %ymm6, %ymm6
; AVX512F-NEXT:    vpmulld %ymm3, %ymm1, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm6, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm5, %ymm1
; AVX512F-NEXT:    vpmulld %ymm4, %ymm2, %ymm2
; AVX512F-NEXT:    vpmulld %ymm0, %ymm3, %ymm0
; AVX512F-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX512F-NEXT:    vpor %ymm0, %ymm1, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: zext_or_mulh_nine_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm2 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm3 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm4 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm0, %ymm5
; AVX512BW-NEXT:    vpmulld %ymm2, %ymm1, %ymm6
; AVX512BW-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX512BW-NEXT:    vpmulld %ymm3, %ymm2, %ymm6
; AVX512BW-NEXT:    vpmulld %ymm4, %ymm3, %ymm7
; AVX512BW-NEXT:    vpor %ymm7, %ymm6, %ymm6
; AVX512BW-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX512BW-NEXT:    vpmulld %ymm0, %ymm4, %ymm6
; AVX512BW-NEXT:    vpmulld %ymm2, %ymm0, %ymm7
; AVX512BW-NEXT:    vpor %ymm7, %ymm6, %ymm6
; AVX512BW-NEXT:    vpmulld %ymm3, %ymm1, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm6, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm5, %ymm1
; AVX512BW-NEXT:    vpmulld %ymm4, %ymm2, %ymm2
; AVX512BW-NEXT:    vpmulld %ymm0, %ymm3, %ymm0
; AVX512BW-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX512BW-NEXT:    vpor %ymm0, %ymm1, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %cw = zext <8 x i16> %c to <8 x i32>
  %dw = zext <8 x i16> %d to <8 x i32>
  %ew = zext <8 x i16> %e to <8 x i32>
  %p0 = mul <8 x i32> %aw, %bw
  %p1 = mul <8 x i32> %bw, %cw
  %p2 = mul <8 x i32> %cw, %dw
  %p3 = mul <8 x i32> %dw, %ew
  %p4 = mul <8 x i32> %ew, %aw
  %p5 = mul <8 x i32> %aw, %cw
  %p6 = mul <8 x i32> %bw, %dw
  %p7 = mul <8 x i32> %cw, %ew
  %p8 = mul <8 x i32> %dw, %aw
  %or0 = or <8 x i32> %p0, %p1
  %or1 = or <8 x i32> %or0, %p2
  %or2 = or <8 x i32> %or1, %p3
  %or3 = or <8 x i32> %or2, %p4
  %or4 = or <8 x i32> %or3, %p5
  %or5 = or <8 x i32> %or4, %p6
  %or6 = or <8 x i32> %or5, %p7
  %or7 = or <8 x i32> %or6, %p8
  %high = lshr <8 x i32> %or7, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @or_mulh_unknown_bits_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i32> %c, <8 x i32> %d) {
; SSE2-LABEL: or_mulh_unknown_bits_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm0, %xmm6
; SSE2-NEXT:    pmulhuw %xmm1, %xmm6
; SSE2-NEXT:    pmullw %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm6[4],xmm1[5],xmm6[5],xmm1[6],xmm6[6],xmm1[7],xmm6[7]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0],xmm6[0],xmm0[1],xmm6[1],xmm0[2],xmm6[2],xmm0[3],xmm6[3]
; SSE2-NEXT:    pshufd {{.*#+}} xmm6 = xmm3[1,1,3,3]
; SSE2-NEXT:    pmuludq %xmm5, %xmm3
; SSE2-NEXT:    pshufd {{.*#+}} xmm3 = xmm3[0,2,2,3]
; SSE2-NEXT:    pshufd {{.*#+}} xmm5 = xmm5[1,1,3,3]
; SSE2-NEXT:    pmuludq %xmm6, %xmm5
; SSE2-NEXT:    pshufd {{.*#+}} xmm5 = xmm5[0,2,2,3]
; SSE2-NEXT:    punpckldq {{.*#+}} xmm3 = xmm3[0],xmm5[0],xmm3[1],xmm5[1]
; SSE2-NEXT:    por %xmm1, %xmm3
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm2[1,1,3,3]
; SSE2-NEXT:    pmuludq %xmm4, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm2 = xmm2[0,2,2,3]
; SSE2-NEXT:    pshufd {{.*#+}} xmm4 = xmm4[1,1,3,3]
; SSE2-NEXT:    pmuludq %xmm1, %xmm4
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm4[0,2,2,3]
; SSE2-NEXT:    punpckldq {{.*#+}} xmm2 = xmm2[0],xmm1[0],xmm2[1],xmm1[1]
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    psrad $16, %xmm3
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm3, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: or_mulh_unknown_bits_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpmulld %ymm3, %ymm2, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: or_mulh_unknown_bits_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpmulld %ymm3, %ymm2, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: or_mulh_unknown_bits_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmulld %ymm3, %ymm2, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %c, %d
  %joined = or <8 x i32> %ab, %cd
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

define <8 x i16> @or_mulh_non_product_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i32> %c) {
; SSE2-LABEL: or_mulh_non_product_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm0, %xmm4
; SSE2-NEXT:    pmulhuw %xmm1, %xmm4
; SSE2-NEXT:    pmullw %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm4[4],xmm1[5],xmm4[5],xmm1[6],xmm4[6],xmm1[7],xmm4[7]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0],xmm4[0],xmm0[1],xmm4[1],xmm0[2],xmm4[2],xmm0[3],xmm4[3]
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    por %xmm3, %xmm1
; SSE2-NEXT:    psrad $16, %xmm1
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm1, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: or_mulh_non_product_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: or_mulh_non_product_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpor %ymm2, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: or_mulh_non_product_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpor %ymm2, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = zext <8 x i16> %a to <8 x i32>
  %bw = zext <8 x i16> %b to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %joined = or <8 x i32> %ab, %c
  %high = lshr <8 x i32> %joined, splat (i32 16)
  %result = trunc <8 x i32> %high to <8 x i16>
  ret <8 x i16> %result
}

; Keep the wide inputs live for the sum. Narrowing each input adds packing
; instead of removing wide work from the reduction.
define { <8 x i16>, <8 x i32> } @or_mulh_non_free_inputs_v8i16(<8 x i32> %a, <8 x i32> %b, <8 x i32> %c, <8 x i32> %d) {
; SSE2-LABEL: or_mulh_non_free_inputs_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pslld $16, %xmm1
; SSE2-NEXT:    psrad $16, %xmm1
; SSE2-NEXT:    pslld $16, %xmm0
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    pslld $16, %xmm3
; SSE2-NEXT:    psrad $16, %xmm3
; SSE2-NEXT:    pslld $16, %xmm2
; SSE2-NEXT:    psrad $16, %xmm2
; SSE2-NEXT:    pslld $16, %xmm5
; SSE2-NEXT:    psrad $16, %xmm5
; SSE2-NEXT:    pslld $16, %xmm4
; SSE2-NEXT:    psrad $16, %xmm4
; SSE2-NEXT:    pslld $16, %xmm7
; SSE2-NEXT:    psrad $16, %xmm7
; SSE2-NEXT:    pslld $16, %xmm6
; SSE2-NEXT:    psrad $16, %xmm6
; SSE2-NEXT:    movdqa %xmm2, %xmm8
; SSE2-NEXT:    packssdw %xmm3, %xmm8
; SSE2-NEXT:    paddd %xmm0, %xmm2
; SSE2-NEXT:    movdqa %xmm0, %xmm9
; SSE2-NEXT:    packssdw %xmm1, %xmm9
; SSE2-NEXT:    movdqa %xmm9, %xmm0
; SSE2-NEXT:    pmulhw %xmm8, %xmm0
; SSE2-NEXT:    pmullw %xmm8, %xmm9
; SSE2-NEXT:    movdqa %xmm9, %xmm8
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm8 = xmm8[4],xmm0[4],xmm8[5],xmm0[5],xmm8[6],xmm0[6],xmm8[7],xmm0[7]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm9 = xmm9[0],xmm0[0],xmm9[1],xmm0[1],xmm9[2],xmm0[2],xmm9[3],xmm0[3]
; SSE2-NEXT:    movdqa %xmm6, %xmm10
; SSE2-NEXT:    packssdw %xmm7, %xmm10
; SSE2-NEXT:    paddd %xmm4, %xmm6
; SSE2-NEXT:    movdqa %xmm4, %xmm0
; SSE2-NEXT:    packssdw %xmm5, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm4
; SSE2-NEXT:    pmulhw %xmm10, %xmm4
; SSE2-NEXT:    pmullw %xmm10, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm10
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm10 = xmm10[4],xmm4[4],xmm10[5],xmm4[5],xmm10[6],xmm4[6],xmm10[7],xmm4[7]
; SSE2-NEXT:    por %xmm8, %xmm10
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0],xmm4[0],xmm0[1],xmm4[1],xmm0[2],xmm4[2],xmm0[3],xmm4[3]
; SSE2-NEXT:    por %xmm9, %xmm0
; SSE2-NEXT:    psrad $16, %xmm10
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm10, %xmm0
; SSE2-NEXT:    paddd %xmm1, %xmm3
; SSE2-NEXT:    paddd %xmm5, %xmm7
; SSE2-NEXT:    paddd %xmm3, %xmm7
; SSE2-NEXT:    paddd %xmm2, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm1
; SSE2-NEXT:    movdqa %xmm7, %xmm2
; SSE2-NEXT:    retq
;
; AVX2-LABEL: or_mulh_non_free_inputs_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpslld $16, %ymm0, %ymm0
; AVX2-NEXT:    vpsrad $16, %ymm0, %ymm4
; AVX2-NEXT:    vpslld $16, %ymm1, %ymm0
; AVX2-NEXT:    vpsrad $16, %ymm0, %ymm1
; AVX2-NEXT:    vpslld $16, %ymm2, %ymm0
; AVX2-NEXT:    vpsrad $16, %ymm0, %ymm2
; AVX2-NEXT:    vpslld $16, %ymm3, %ymm0
; AVX2-NEXT:    vpsrad $16, %ymm0, %ymm3
; AVX2-NEXT:    vpmulld %ymm1, %ymm4, %ymm0
; AVX2-NEXT:    vpmulld %ymm3, %ymm2, %ymm5
; AVX2-NEXT:    vpor %ymm5, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm5
; AVX2-NEXT:    vpackusdw %xmm5, %xmm0, %xmm0
; AVX2-NEXT:    vpaddd %ymm1, %ymm4, %ymm1
; AVX2-NEXT:    vpaddd %ymm3, %ymm2, %ymm2
; AVX2-NEXT:    vpaddd %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: or_mulh_non_free_inputs_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpslld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrad $16, %ymm0, %ymm4
; AVX512F-NEXT:    vpslld $16, %ymm1, %ymm0
; AVX512F-NEXT:    vpsrad $16, %ymm0, %ymm1
; AVX512F-NEXT:    vpslld $16, %ymm2, %ymm0
; AVX512F-NEXT:    vpsrad $16, %ymm0, %ymm2
; AVX512F-NEXT:    vpslld $16, %ymm3, %ymm0
; AVX512F-NEXT:    vpsrad $16, %ymm0, %ymm3
; AVX512F-NEXT:    vpmulld %ymm1, %ymm4, %ymm0
; AVX512F-NEXT:    vpmulld %ymm3, %ymm2, %ymm5
; AVX512F-NEXT:    vpor %ymm5, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    vpaddd %ymm1, %ymm4, %ymm1
; AVX512F-NEXT:    vpaddd %ymm3, %ymm2, %ymm2
; AVX512F-NEXT:    vpaddd %ymm2, %ymm1, %ymm1
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: or_mulh_non_free_inputs_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpslld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrad $16, %ymm0, %ymm4
; AVX512BW-NEXT:    vpslld $16, %ymm1, %ymm0
; AVX512BW-NEXT:    vpsrad $16, %ymm0, %ymm1
; AVX512BW-NEXT:    vpslld $16, %ymm2, %ymm0
; AVX512BW-NEXT:    vpsrad $16, %ymm0, %ymm2
; AVX512BW-NEXT:    vpslld $16, %ymm3, %ymm0
; AVX512BW-NEXT:    vpsrad $16, %ymm0, %ymm3
; AVX512BW-NEXT:    vpmulld %ymm1, %ymm4, %ymm0
; AVX512BW-NEXT:    vpmulld %ymm3, %ymm2, %ymm5
; AVX512BW-NEXT:    vpor %ymm5, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    vpaddd %ymm1, %ymm4, %ymm1
; AVX512BW-NEXT:    vpaddd %ymm3, %ymm2, %ymm2
; AVX512BW-NEXT:    vpaddd %ymm2, %ymm1, %ymm1
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    retq
  %al = shl <8 x i32> %a, splat(i32 16)
  %as = ashr <8 x i32> %al, splat(i32 16)
  %bl = shl <8 x i32> %b, splat(i32 16)
  %bs = ashr <8 x i32> %bl, splat(i32 16)
  %cl = shl <8 x i32> %c, splat(i32 16)
  %cs = ashr <8 x i32> %cl, splat(i32 16)
  %dl = shl <8 x i32> %d, splat(i32 16)
  %ds = ashr <8 x i32> %dl, splat(i32 16)
  %ab = mul <8 x i32> %as, %bs
  %cd = mul <8 x i32> %cs, %ds
  %joined = or <8 x i32> %ab, %cd
  %hi = lshr <8 x i32> %joined, splat(i32 16)
  %result = trunc <8 x i32> %hi to <8 x i16>
  %sum_ab = add <8 x i32> %as, %bs
  %sum_cd = add <8 x i32> %cs, %ds
  %sum = add <8 x i32> %sum_ab, %sum_cd
  %ret0 = insertvalue { <8 x i16>, <8 x i32> } poison, <8 x i16> %result, 0
  %ret1 = insertvalue { <8 x i16>, <8 x i32> } %ret0, <8 x i32> %sum, 1
  ret { <8 x i16>, <8 x i32> } %ret1
}

; Do not add byte-to-word extensions to recover the high-half reduction.
define <8 x i16> @or_mulh_smaller_inputs_v8i16(<8 x i8> %a, <8 x i16> %b, <8 x i8> %c, <8 x i16> %d) {
; SSE2-LABEL: or_mulh_smaller_inputs_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pxor %xmm4, %xmm4
; SSE2-NEXT:    movdqa %xmm1, %xmm5
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm5 = xmm5[4],xmm4[4],xmm5[5],xmm4[5],xmm5[6],xmm4[6],xmm5[7],xmm4[7]
; SSE2-NEXT:    punpcklbw {{.*#+}} xmm6 = xmm6[0],xmm0[0],xmm6[1],xmm0[1],xmm6[2],xmm0[2],xmm6[3],xmm0[3],xmm6[4],xmm0[4],xmm6[5],xmm0[5],xmm6[6],xmm0[6],xmm6[7],xmm0[7]
; SSE2-NEXT:    psraw $8, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm7
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm7 = xmm7[4,4,5,5,6,6,7,7]
; SSE2-NEXT:    pmaddwd %xmm5, %xmm7
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm1 = xmm1[0],xmm4[0],xmm1[1],xmm4[1],xmm1[2],xmm4[2],xmm1[3],xmm4[3]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm6 = xmm6[0,0,1,1,2,2,3,3]
; SSE2-NEXT:    pmaddwd %xmm1, %xmm6
; SSE2-NEXT:    movdqa %xmm3, %xmm1
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm1 = xmm1[4],xmm4[4],xmm1[5],xmm4[5],xmm1[6],xmm4[6],xmm1[7],xmm4[7]
; SSE2-NEXT:    punpcklbw {{.*#+}} xmm0 = xmm0[0],xmm2[0],xmm0[1],xmm2[1],xmm0[2],xmm2[2],xmm0[3],xmm2[3],xmm0[4],xmm2[4],xmm0[5],xmm2[5],xmm0[6],xmm2[6],xmm0[7],xmm2[7]
; SSE2-NEXT:    psraw $8, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm2
; SSE2-NEXT:    punpckhwd {{.*#+}} xmm2 = xmm2[4,4,5,5,6,6,7,7]
; SSE2-NEXT:    pmaddwd %xmm1, %xmm2
; SSE2-NEXT:    por %xmm7, %xmm2
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm3 = xmm3[0],xmm4[0],xmm3[1],xmm4[1],xmm3[2],xmm4[2],xmm3[3],xmm4[3]
; SSE2-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0,0,1,1,2,2,3,3]
; SSE2-NEXT:    pmaddwd %xmm3, %xmm0
; SSE2-NEXT:    por %xmm6, %xmm0
; SSE2-NEXT:    psrad $16, %xmm2
; SSE2-NEXT:    psrad $16, %xmm0
; SSE2-NEXT:    packssdw %xmm2, %xmm0
; SSE2-NEXT:    retq
;
; AVX2-LABEL: or_mulh_smaller_inputs_v8i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmovsxbd %xmm0, %ymm0
; AVX2-NEXT:    vpmovsxbd %xmm2, %ymm2
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX2-NEXT:    vpmaddwd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX2-NEXT:    vpmaddwd %ymm1, %ymm2, %ymm1
; AVX2-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpackusdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512F-LABEL: or_mulh_smaller_inputs_v8i16:
; AVX512F:       # %bb.0:
; AVX512F-NEXT:    vpmovsxbd %xmm0, %ymm0
; AVX512F-NEXT:    vpmovsxbd %xmm2, %ymm2
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512F-NEXT:    vpmaddwd %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512F-NEXT:    vpmaddwd %ymm1, %ymm2, %ymm1
; AVX512F-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512F-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512F-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512F-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512F-NEXT:    vzeroupper
; AVX512F-NEXT:    retq
;
; AVX512BW-LABEL: or_mulh_smaller_inputs_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpmovsxbd %xmm0, %ymm0
; AVX512BW-NEXT:    vpmovsxbd %xmm2, %ymm2
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; AVX512BW-NEXT:    vpmaddwd %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
; AVX512BW-NEXT:    vpmaddwd %ymm1, %ymm2, %ymm1
; AVX512BW-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vpsrld $16, %ymm0, %ymm0
; AVX512BW-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512BW-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
  %aw = sext <8 x i8> %a to <8 x i32>
  %bw = sext <8 x i16> %b to <8 x i32>
  %cw = sext <8 x i8> %c to <8 x i32>
  %dw = sext <8 x i16> %d to <8 x i32>
  %ab = mul <8 x i32> %aw, %bw
  %cd = mul <8 x i32> %cw, %dw
  %joined = or <8 x i32> %ab, %cd
  %hi = lshr <8 x i32> %joined, splat(i32 16)
  %result = trunc <8 x i32> %hi to <8 x i16>
  ret <8 x i16> %result
}

; Constants can be narrowed at compile time.
define <8 x i16> @or_mulh_constant_inputs_v8i16(<8 x i16> %a, <8 x i16> %b) {
; SSE2-LABEL: or_mulh_constant_inputs_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pmulhw {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0 # [7,13,29,57,115,231,463,929]
; SSE2-NEXT:    pmulhw {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1 # [17,23,37,43,61,71,83,97]
; SSE2-NEXT:    por %xmm1, %xmm0
; SSE2-NEXT:    retq
;
; AVX-LABEL: or_mulh_constant_inputs_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpmulhw {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0 # [7,13,29,57,115,231,463,929]
; AVX-NEXT:    vpmulhw {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1, %xmm1 # [17,23,37,43,61,71,83,97]
; AVX-NEXT:    vpor %xmm0, %xmm1, %xmm0
; AVX-NEXT:    retq
  %aw = sext <8 x i16> %a to <8 x i32>
  %bw = sext <8 x i16> %b to <8 x i32>
  %ab = mul <8 x i32> %aw, <i32 7, i32 13, i32 29, i32 57, i32 115, i32 231, i32 463, i32 929>
  %cd = mul <8 x i32> %bw, <i32 17, i32 23, i32 37, i32 43, i32 61, i32 71, i32 83, i32 97>
  %joined = or <8 x i32> %ab, %cd
  %hi = lshr <8 x i32> %joined, splat(i32 16)
  %result = trunc <8 x i32> %hi to <8 x i16>
  ret <8 x i16> %result
}
